# TetLab Spiral A1 — deterministic procedural test corpus.
# Provenance [MEASURED-PROVENANCE]: every mesh is generated by this file,
# parameterized by loop index math only — no RNG anywhere. Regenerating the
# corpus on any machine yields byte-identical OBJs (hashes in manifest.csv).
#
# Classes (Spiral B requirements, seeded here):
#   analytic control .... cube, icosphere
#   thin geometry ....... plate, grass clump (crossed tapered blades)
#   WGE conifer proxy ... stacked tapered foliage-card tiers + trunk
#   dense smooth ........ blob (high-subdiv icosphere, thousands of tris)
#   negative controls ... skeleton (open tube = topology-changing stand-in),
#                         robot (sharp creases = joint-discontinuity stand-in),
#                         teapot (closed surface = rigid-prop stand-in)
#
# NOTE: paper's Frog/Tree/Grass objects are commercial models (cgtrader/
#       sketchfab) and cannot be pinned; these proxies stand in [UNKNOWN->
#       MEASURED once real WGE content lands in the corpus].
module TetCorpus

using SHA

export build_corpus!, corpus_manifest

const ROOT = dirname(@__DIR__)   # TetLab/

# ---------- writers (18-digit fixed point; parse-identical) ----------
_fx(x) = (isfinite(x) || error("non-finite coord"); 
          (x < 0 ? "-" : "") * begin a = abs(x); ip = floor(Int, a)
          fp = round(Int, (a - ip) * 1e12); fp == 1_000_000_000_000 && (ip += 1; fp = 0)
          string(ip) * "." * lpad(string(fp), 12, '0') end)

function write_obj(path, V, T)
    open(path, "w") do io
        for v in V; println(io, "v ", _fx(v[1]), " ", _fx(v[2]), " ", _fx(v[3])); end
        for t in T; println(io, "f ", t[1] + 1, " ", t[2] + 1, " ", t[3] + 1); end
    end
end
mesh_sha(path) = bytes2hex(sha256(read(path)))

# ---------- generators ----------

function cube(s = 1.0)
    V = [(0.,0.,0.),(s,0.,0.),(0.,s,0.),(0.,0.,s),(s,s,0.),(s,0.,s),(0.,s,s),(s,s,s)]
    # canonical cube face list (quad -> two tris)
    quads = [(1,2,5,3),(1,3,7,4),(1,4,6,2),(4,7,8,6),(2,6,8,5),(3,5,8,7)]
    T = NTuple{3,Int}[]
    for (a,b,c,d) in quads
        push!(T, (a-1,b-1,c-1), (a-1,c-1,d-1))
    end
    return V, T
end

function icosphere(subdiv::Int; radius = 1.0, center = (0.0, 0.0, 0.0))
    t = (1 + sqrt(5)) / 2
    verts0 = NTuple{3,Float64}[(-1,t,0),(1,t,0),(-1,-t,0),(1,-t,0),
                               (0,-1,t),(0,1,t),(0,-1,-t),(0,1,-t),
                               (t,0,-1),(t,0,1),(-t,0,-1),(-t,0,1)]
    verts = [begin
                s = sqrt(c[1]^2 + c[2]^2 + c[3]^2)
                (c[1]/s, c[2]/s, c[3]/s)
             end for c in verts0]
    # DERIVE the face list from geometry — never recall it. (A recalled
    # "standard" list was falsified here: 19/20 faces were not icosahedron
    # faces. RPD ledger F-A1.1.)
    d2(i, j) = sum(abs2, verts[i] .- verts[j])
    mind = minimum(d2(i, j) for i in 1:12, j in 1:12 if i < j)
    edges = Set{Tuple{Int,Int}}()
    for i in 1:12, j in 1:12
        i < j && d2(i, j) < mind * 1.05 && push!(edges, (i, j))
    end
    faces1 = Tuple{Int,Int,Int}[]
    for i in 1:10, j in i+1:11, k in j+1:12
        ((i, j) in edges && (j, k) in edges && (i, k) in edges) || continue
        # orient outward: normal . centroid-direction > 0 for origin-centered convex
        a, b, c = verts[i], verts[j], verts[k]
        n = (a[1]*(b[2]-c[2]) + a[2]*(b[3]-c[3]) + a[3]*(b[1]-c[1])) -
            (b[1]*(a[2]-c[2]) + b[2]*(a[3]-c[3]) + b[3]*(a[1]-c[1]))
        # scalar triple (b-a)x(c-a).z-equivalent is unreliable in 3D; use cross:
        u = b .- a; w = c .- a
        nx = u[2]*w[3] - u[3]*w[2]
        ny = u[3]*w[1] - u[1]*w[3]
        nz = u[1]*w[2] - u[2]*w[1]
        cen = ((a[1]+b[1]+c[1])/3, (a[2]+b[2]+c[2])/3, (a[3]+b[3]+c[3])/3)
        if nx*cen[1] + ny*cen[2] + nz*cen[3] > 0
            push!(faces1, (i, j, k))
        else
            push!(faces1, (i, k, j))
        end
    end
    @assert length(faces1) == 20 "icosahedron derivation produced $(length(faces1)) faces"
    faces = [(f[1]-1, f[2]-1, f[3]-1) for f in faces1]
    # Single mutable array, NEVER rebound: the midpoint closure below captures
    # this binding. (A rebinding here is exactly what produced stale-index NaNs.)
    if radius != 1.0 || center != (0.0, 0.0, 0.0)
        verts = [(center[1] + radius * v[1],
                  center[2] + radius * v[2],
                  center[3] + radius * v[3]) for v in verts]
    end
    V = verts
    T = faces
    cache = Dict{Tuple{Int,Int},Int}()
    function midpoint(a, b)
        key = a < b ? (a, b) : (b, a)
        get!(cache, key) do
            pa, pb = V[a+1], V[b+1]
            m = ((pa[1]+pb[1])/2, (pa[2]+pb[2])/2, (pa[3]+pb[3])/2)
            n = sqrt(m[1]^2 + m[2]^2 + m[3]^2)
            push!(V, (m[1]/n, m[2]/n, m[3]/n))
            length(V) - 1
        end
    end
    for _ in 1:subdiv
        T2 = NTuple{3,Int}[]
        for (a,b,c) in T
            ab, bc, ca = midpoint(a,b), midpoint(b,c), midpoint(c,a)
            push!(T2, (a,ab,ca),(b,bc,ab),(c,ca,bc),(ab,bc,ca))
        end
        T = T2
    end
    return V, T
end

function plate(w = 1.0, h = 1.0, nx = 16, ny = 16)
    V = NTuple{3,Float64}[]; T = NTuple{3,Int}[]
    for j in 0:ny, i in 0:nx
        push!(V, (w*i/nx, h*j/ny, 0.002*sin(0.7*i + 1.3*j)))  # gentle fixed ripple
    end
    id(i, j) = j*(nx+1) + i + 1
    for j in 1:ny, i in 1:nx
        push!(T, (id(i-1,j-1)-1, id(i,j-1)-1, id(i,j)-1))
        push!(T, (id(i-1,j-1)-1, id(i,j)-1,   id(i-1,j)-1))
    end
    return V, T
end

function grass_clump()
    # 12 blades: each a tapered strip bent by index math; two crossing quads per blade.
    V = NTuple{3,Float64}[]; T = NTuple{3,Int}[]
    for b in 0:11
        θ = 2π * b / 12; ca, sa = cos(θ), sin(θ)
        lean = 0.35 * sin(0.9 * b + 0.4)
        h = 0.55 + 0.25 * abs(sin(1.7 * b))
        for k in 0:4
            t = k / 4; halfw = 0.03 * (1 - 0.85 * t)
            x = ca * 0.10 * (1 - t) + lean * t * t
            y = h * t
            z = sa * 0.10 * (1 - t)
            push!(V, (x - halfw*sa, y, z + halfw*ca))   # left edge
            push!(V, (x + halfw*sa, y, z - halfw*ca))   # right edge
        end
        base = b * 10
        for k in 1:4
            a0 = base + 2*(k-1)
            push!(T, (a0, a0+1, a0+3), (a0, a0+3, a0+2))
        end
    end
    return V, T
end

function conifer_proxy(tiers = 10, sectors = 10, gw = 6, gh = 4)
    # Dense tapered card-grid tiers + trunk prism. WGE conifer stand-in with
    # canopy-like density (~4.8k tris); a 152-tri version was rejected as
    # unrepresentative (savings law: far below the 81 tris/tet threshold).
    V = NTuple{3,Float64}[]; T = NTuple{3,Int}[]
    r0 = 0.55
    for ti in 0:tiers-1
        y0 = 0.28 + 0.62*ti
        y1 = y0 + 0.75
        r = r0 * (1 - 0.85 * ti / (tiers - 1))
        for k in 0:sectors-1
            φ = 2π * k / sectors + 0.35 * ti                 # fixed twist
            ca, sa = cos(φ), sin(φ)
            P0 = (r*ca, y0, r*sa)                            # outer base point
            P1 = (0.25*ca, y1, 0.25*sa)                      # tip (inward + up)
            tangent = (-sa, 0.0, ca)
            width = 2π * r / sectors * 0.8                   # gap, no overlap
            base = length(V)
            for j in 0:gh, i in 0:gw
                s = i / gw; t = j / gh
                bx = P0[1] + t*(P1[1]-P0[1])
                by = P0[2] + t*(P1[2]-P0[2])
                bz = P0[3] + t*(P1[3]-P0[3])
                w = width * (1 - 0.6*t)                      # taper to tip
                push!(V, (bx + (s-0.5)*w*tangent[1], by, bz + (s-0.5)*w*tangent[3]))
            end
            idx(i, j) = base + j*(gw+1) + i + 1
            for i in 1:gw, j in 1:gh
                a, b = idx(i-1, j-1), idx(i, j-1)
                c, d = idx(i, j),   idx(i-1, j)
                push!(T, (a-1, b-1, c-1), (a-1, c-1, d-1))
            end
        end
    end
    # trunk as thin 4-side prism
    tv = [( -0.03,0.,-0.03),(0.03,0.,-0.03),(0.03,0.,0.03),(-0.03,0.,0.03),
          ( -0.015,1.1,-0.015),(0.015,1.1,-0.015),(0.015,1.1,0.015),(-0.015,1.1,0.015)]
    for v in tv; push!(V, v); end
    b = length(V) - 8
    for (a,c,d) in ((1,2,6),(1,6,5),(2,3,7),(2,7,6),(3,4,8),(3,8,7),(4,1,5),(4,5,8))
        push!(T, (b+a-1, b+c-1, b+d-1))
    end
    return V, T
end

function blob(subdiv = 5)
    V, T = icosphere(subdiv)
    # radial displacement by index math (deterministic "terrain-ish" lumpiness)
    V = [begin
            r = 1 + 0.08 * sin(5.1*v[1] + 3.7*v[2]) * cos(4.3*v[3] + 1.1)
            (v[1]*r, v[2]*r, v[3]*r)
         end for v in V]
    return V, T
end

function open_tube(r = 0.4, h = 1.2, n = 24, m = 6)
    # no caps -> boundary edges -> topology-change stand-in (cutting class)
    V = NTuple{3,Float64}[]; T = NTuple{3,Int}[]
    for j in 0:m, i in 0:n-1
        φ = 2π*i/n; y = h*j/m
        push!(V, (r*cos(φ), y, r*sin(φ)))
    end
    id(i, j) = j*n + (i % n) + 1
    for j in 1:m, i in 0:n-1
        push!(T, (id(i,j-1)-1, id(i+1,j-1)-1, id(i+1,j)-1))
        push!(T, (id(i,j-1)-1, id(i+1,j)-1,   id(i,j)-1))
    end
    return V, T
end

function creased_robot()
    # boxes at fixed offsets -> sharp weight-discontinuity stand-in
    V = NTuple{3,Float64}[]; T = NTuple{3,Int}[]
    function box(cx, cy, cz, sx, sy, sz)
        base = length(V)
        for (dx,dy,dz) in ((-1,-1,-1),(1,-1,-1),(1,1,-1),(-1,1,-1),
                           (-1,-1,1),(1,-1,1),(1,1,1),(-1,1,1))
            push!(V, (cx+sx*dx/2, cy+sy*dy/2, cz+sz*dz/2))
        end
        b = base
        for (a,c,d) in ((1,2,3),(1,3,4),(5,8,7),(5,7,6),(1,5,6),(1,6,2),
                        (2,6,7),(2,7,3),(3,7,8),(3,8,4),(4,8,5),(4,5,1))
            push!(T, (b+a-1, b+c-1, b+d-1))
        end
    end
    box(0, 0.55, 0, 0.36, 0.5, 0.24)     # torso
    box(0, 1.0,  0, 0.18, 0.3, 0.18)     # head
    box(-0.3, 0.5, 0, 0.12, 0.45, 0.12)  # arms
    box( 0.3, 0.5, 0, 0.12, 0.45, 0.12)
    box(-0.12, 0.12, 0, 0.13, 0.28, 0.13) # legs
    box( 0.12, 0.12, 0, 0.13, 0.28, 0.13)
    return V, T
end

function torus(R = 0.7, r = 0.25, n = 28, m = 14)
    # closed genus-1 surface = rigid-prop stand-in (closed, no deformation)
    V = NTuple{3,Float64}[]; T = NTuple{3,Int}[]
    for i in 0:n-1, j in 0:m-1
        u = 2π*i/n; v = 2π*j/m
        push!(V, ((R + r*cos(v))*cos(u), r*sin(v), (R + r*cos(v))*sin(u)))
    end
    id(i, j) = (i % n)*m + (j % m) + 1
    for i in 0:n-1, j in 0:m-1
        a, b, c, d = id(i,j), id(i+1,j), id(i+1,j+1), id(i,j+1)
        push!(T, (a-1, b-1, c-1), (a-1, c-1, d-1))
    end
    return V, T
end

# ---------- corpus driver ----------

const SPECS = [
    ("cube",      () -> cube(),                     "analytic control"),
    ("icosphere2",() -> icosphere(2),               "analytic control"),
    ("plate",     () -> plate(),                    "thin foliage card"),
    ("grass",     () -> grass_clump(),              "thin grass clump"),
    ("conifer",   () -> conifer_proxy(),            "WGE conifer proxy"),
    ("blob",      () -> blob(5),                    "dense smooth foliage"),
    ("skeleton",  () -> open_tube(),                "NEG CTRL topology-change"),
    ("robot",     () -> creased_robot(),            "NEG CTRL weight discontinuity"),
    ("teapot",    () -> torus(),                    "NEG CTRL rigid prop"),
]

function build_corpus!()
    dir = joinpath(ROOT, "corpus"); isdir(dir) || mkdir(dir)
    rows = String[]
    for (name, gen, role) in SPECS
        V, T = gen()
        path = joinpath(dir, name * ".obj")
        write_obj(path, V, T)
        push!(rows, join([name, string(length(V)), string(length(T)), role, mesh_sha(path)], ","))
        @info "corpus" name verts=length(V) tris=length(T)
    end
    manifest = joinpath(dir, "manifest.csv")
    open(manifest, "w") do io
        println(io, "name,verts,tris,role,sha256")
        foreach(r -> println(io, r), rows)
    end
    return dir, manifest
end

corpus_manifest() = joinpath(ROOT, "corpus", "manifest.csv")

end # module
